name: Tests
on: [pull_request]
jobs:
  validate_schemas:
    name: Validate JSON Schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate People JSON schema
        uses: GrantBirki/json-yaml-validate@v2.3.0
        with:
          json_schema: ./schemas/people-schema.json
          base_dir: './people'

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
